/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { BigIncABI } from "./BigIncABI";
export * as factories from "./factories";
export { BigIncABI__factory } from "./factories/BigIncABI__factory";
